/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../errors";
import * as SueljeApi from "../../..";

export class MovieDoesNotExistError extends errors.SueljeApiError {
    constructor(body: SueljeApi.MovieId) {
        super({
            message: "MovieDoesNotExistError",
            statusCode: 404,
            body: body,
        });
        Object.setPrototypeOf(this, MovieDoesNotExistError.prototype);
    }
}
