/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as core from "../../../../core";
import * as SueljeApi from "../../..";
import * as serializers from "../../../../serialization";
import urlJoin from "url-join";
import * as errors from "../../../../errors";

export declare namespace Imdb {
    interface Options {
        environment: core.Supplier<string>;
    }
}

export class Imdb {
    constructor(protected readonly options: Imdb.Options) {}

    /**
     * Add a movie to the database
     */
    public async createMovie(request: SueljeApi.CreateMovieRequest): Promise<SueljeApi.MovieId> {
        const _response = await core.fetcher({
            url: urlJoin(await core.Supplier.get(this.options.environment), "/movies/create-movie"),
            method: "POST",
            headers: {
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "fernstart",
                "X-Fern-SDK-Version": "0.0.53",
            },
            contentType: "application/json",
            body: await serializers.CreateMovieRequest.jsonOrThrow(request, { unrecognizedObjectKeys: "strip" }),
            timeoutMs: 60000,
        });
        if (_response.ok) {
            return await serializers.MovieId.parseOrThrow(_response.body, {
                unrecognizedObjectKeys: "passthrough",
                allowUnrecognizedUnionMembers: true,
                allowUnrecognizedEnumValues: true,
                breadcrumbsPrefix: ["response"],
            });
        }

        if (_response.error.reason === "status-code") {
            throw new errors.SueljeApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SueljeApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.SueljeApiTimeoutError();
            case "unknown":
                throw new errors.SueljeApiError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * Retrieve a movie from the database based on the ID
     * @throws {@link SueljeApi.MovieDoesNotExistError}
     */
    public async getMovie(id: SueljeApi.MovieId): Promise<SueljeApi.Movie> {
        const _response = await core.fetcher({
            url: urlJoin(
                await core.Supplier.get(this.options.environment),
                `/movies/${await serializers.MovieId.jsonOrThrow(id)}`
            ),
            method: "GET",
            headers: {
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "fernstart",
                "X-Fern-SDK-Version": "0.0.53",
            },
            contentType: "application/json",
            timeoutMs: 60000,
        });
        if (_response.ok) {
            return await serializers.Movie.parseOrThrow(_response.body, {
                unrecognizedObjectKeys: "passthrough",
                allowUnrecognizedUnionMembers: true,
                allowUnrecognizedEnumValues: true,
                breadcrumbsPrefix: ["response"],
            });
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new SueljeApi.MovieDoesNotExistError(
                        await serializers.MovieId.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        })
                    );
                default:
                    throw new errors.SueljeApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SueljeApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.SueljeApiTimeoutError();
            case "unknown":
                throw new errors.SueljeApiError({
                    message: _response.error.errorMessage,
                });
        }
    }
}
