"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SueljeApiTimeoutError = void 0;
class SueljeApiTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, SueljeApiTimeoutError.prototype);
    }
}
exports.SueljeApiTimeoutError = SueljeApiTimeoutError;
