/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SueljeApi from "../../../../api";
import * as core from "../../../../core";

export const MovieId: core.serialization.Schema<serializers.MovieId.Raw, SueljeApi.MovieId> =
    core.serialization.string();

export declare namespace MovieId {
    type Raw = string;
}
