/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SueljeApi from "../../..";

export interface Movie {
    id: SueljeApi.MovieId;
    title: string;
    /** The rating scale out of ten stars */
    rating: number;
}
